using ProfitNx.CRM.Models;

namespace ProfitNx.CRM.Services;

public static class PermissionCatalog
{
    public static List<PermissionItem> Definitions() => new()
    {
        Item("Dashboard", "dashboard.view", "Dashboard View"),
        Item("Dashboard", "dashboard.live", "Live Dashboard (Main Overview)"),
        Item("Dashboard", "dashboard.kpi", "Dashboard KPI Cards"),
        Item("Dashboard", "dashboard.business", "Business Summary Blocks"),
        Item("Dashboard", "dashboard.focus", "Smart Focus Plan"),

        Item("Inquiry Menu", "inquiry.view", "Inquiry View"),
        Item("Inquiry Menu", "inquiry.create", "Inquiry Create"),
        Item("Inquiry Menu", "inquiry.create.support", "Support / Partner Quick Create"),
        Item("Inquiry Menu", "inquiry.edit", "Inquiry Edit"),
        Item("Inquiry Menu", "inquiry.delete", "Inquiry Delete"),
        Item("Inquiry Menu", "inquiry.documents.send", "Send Quotation / Documents (Email & WhatsApp)"),
        Item("Inquiry Menu", "inquiry.status", "Inquiry Status Update"),
        Item("Inquiry Menu", "inquiry.assign.admin", "Assign / Forward To Admin"),
        Item("Inquiry Menu", "inquiry.assign.user", "Assign / Forward To User"),
        Item("Inquiry Menu", "inquiry.assign.partner", "Assign / Forward To Partner"),

        Item("Inquiry Fields", "field.inquiry.date", "Inquiry Date Field"),
        Item("Inquiry Fields", "field.inquiry.submittedby", "Submitted By Field"),
        Item("Inquiry Fields", "field.inquiry.source", "Source Field"),
        Item("Inquiry Fields", "field.inquiry.customerinfo", "Customer / Company Fields"),
        Item("Inquiry Fields", "field.inquiry.contact", "Mobile / Email / Contact Person Fields"),
        Item("Inquiry Fields", "field.inquiry.city", "City / State Fields"),
        Item("Inquiry Fields", "field.inquiry.product", "Product / Version Interest Fields"),
        Item("Inquiry Fields", "field.inquiry.amount", "Amount / License Fields"),
        Item("Inquiry Fields", "field.inquiry.support", "Support Executive Field"),
        Item("Inquiry Fields", "field.inquiry.user", "Assigned User Field"),
        Item("Inquiry Fields", "field.inquiry.partner", "Partner Field"),
        Item("Inquiry Fields", "field.inquiry.status", "Status Fields"),
        Item("Inquiry Fields", "field.inquiry.sold", "Sold License / Bill Fields"),
        Item("Inquiry Fields", "field.inquiry.close", "Close Reason Fields"),
        Item("Inquiry Fields", "field.inquiry.remarks", "Remarks / Requirement Fields"),
        Item("Inquiry Fields", "field.inquiry.followup", "Follow-up Fields"),

        Item("Inquiry Smart Features", "inquiry.report.view", "My Inquiry Report"),
        Item("Inquiry Smart Features", "inquiry.followup.reminder.view", "Follow-up Reminder / List"),
        Item("Inquiry Smart Features", "inquiry.smartfilters.view", "Smart Focus Filters"),
        Item("Inquiry Smart Features", "inquiry.conversion.score.view", "Conversion Score"),
        Item("Inquiry Smart Features", "inquiry.nextbestaction.view", "Next Best Action"),
        Item("Inquiry Smart Features", "inquiry.followup.manage", "Follow-up Date / Demo / Note Manage"),
        Item("Inquiry Smart Features", "inquiry.quickdate.manage", "Quick Follow-up Date Buttons"),
        Item("Inquiry Smart Features", "inquiry.quickstage.manage", "Quick Stage Buttons"),
        Item("Inquiry Smart Features", "inquiry.timeline.view", "Full Status Timeline"),
        Item("Inquiry Smart Features", "inquiry.contact.call", "Call Customer Button"),
        Item("Inquiry Smart Features", "inquiry.contact.whatsapp", "WhatsApp Customer Button"),
        Item("Inquiry Smart Features", "inquiry.contact.email", "Email Customer Button"),
        Item("Inquiry Smart Features", "inquiry.summary.copy", "Copy Inquiry Summary"),
        Item("My Inquiries Cards", "inquiry.card.total", "Total Card"),
        Item("My Inquiries Cards", "inquiry.card.new", "New Inquiry Card"),
        Item("My Inquiries Cards", "inquiry.card.genuine", "Genuine Card"),
        Item("My Inquiries Cards", "inquiry.card.notgenuine", "Not Genuine Card"),
        Item("My Inquiries Cards", "inquiry.card.followup", "Follow Up Card"),
        Item("My Inquiries Cards", "inquiry.card.demo.scheduled", "Demo Scheduled Card"),
        Item("My Inquiries Cards", "inquiry.card.demo.done", "Demo Done Card"),
        Item("My Inquiries Cards", "inquiry.card.sold", "Sold Card"),
        Item("My Inquiries Cards", "inquiry.card.closed", "Closed Card"),

        Item("Implementation & Training", "implementation.view", "Implementation Menu View"),
        Item("Implementation & Training", "implementation.view.all", "View All Customer Onboarding Records"),
        Item("Implementation & Training", "implementation.create", "Create Implementation / Training Record"),
        Item("Implementation & Training", "implementation.sold.setup", "Ask & Create Implementation After Sold"),
        Item("Implementation & Training", "implementation.edit", "Edit Implementation / Training Workflow"),
        Item("Implementation & Training", "implementation.assign", "Assign Support Head / Team Member"),
        Item("Implementation & Training", "implementation.schedule", "Create / Edit Multi-day Schedule"),
        Item("Implementation & Training", "implementation.progress", "Update Day-wise Covered Points"),
        Item("Implementation & Training", "implementation.transfer", "Transfer Work with OTP Approval"),
        Item("Implementation & Training", "implementation.complete", "Complete Training and Send Feedback"),
        Item("Implementation & Training", "implementation.reopen", "Re-open Completed Record with OTP Approval"),
        Item("Implementation & Training", "implementation.close.notrequired", "Close When Training Is Not Required"),
        Item("Implementation & Training", "implementation.pause", "Pause / Resume Training"),
        Item("Implementation & Training", "implementation.paidtraining", "Create and Maintain Paid Training"),
        Item("Implementation & Training", "implementation.feedback.view", "View Customer Rating and Remarks"),
        Item("Implementation & Training", "implementation.reminder.view", "15-minute CRM Reminder Popup"),
        Item("Implementation & Training", "implementation.ai.view", "Free AI Risk and Next-action Guidance"),
        Item("Implementation & Training", "implementation.delete", "Delete Implementation / Training Record"),
        Item("Implementation Fields", "field.implementation.customer", "Customer Contact Fields"),
        Item("Implementation Fields", "field.implementation.license", "License and Product Fields"),
        Item("Implementation Fields", "field.implementation.pin", "License PIN Field"),
        Item("Implementation Fields", "field.implementation.assignment", "Support Assignment Fields"),
        Item("Implementation Fields", "field.implementation.schedule", "Schedule Fields"),
        Item("Implementation Fields", "field.implementation.progress", "Progress and Covered Points"),
        Item("Implementation Fields", "field.implementation.feedback", "Feedback Rating and Remarks"),

        Item("Reports", "reports.view", "Reports Menu View"),
        Item("Reports", "reports.product", "Product / Version Sold Report"),
        Item("Reports", "reports.partner", "Partner Performance Report"),
        Item("Reports", "reports.user", "User Performance Report"),
        Item("Reports", "reports.support", "Support Team Performance Report"),
        Item("Reports", "reports.admin", "Admin Performance Report"),
        Item("Reports", "reports.detailed", "Detailed Pipeline Grid"),
        Item("Reports", "reports.source", "Total Inquiry List (Source Wise)"),
        Item("Reports", "reports.training", "Implementation / Training Report"),
        Item("Reports Fields", "field.reports.amount", "Report Amount Fields"),
        Item("Reports Fields", "field.reports.export", "Report Export Button"),
        Item("Reports Fields", "field.reports.filter", "Report Filter Fields"),

        Item("Users", "users.view", "Users Menu View"),
        Item("Users", "loginreport.view", "Login History Report & Live Users"),
        Item("Users", "loginreport.delete", "Login History Delete (Single / All)"),
        Item("Users", "users.manage", "Users Create/Edit/Delete"),
        Item("Users Fields", "field.user.fullname", "Full Name Field"),
        Item("Users Fields", "field.user.username", "Username Field"),
        Item("Users Fields", "field.user.password", "Password Field"),
        Item("Users Fields", "field.user.role", "Role Field"),
        Item("Users Fields", "field.user.mobile", "Mobile Field"),
        Item("Users Fields", "field.user.email", "Email Field"),
        Item("Users Fields", "field.user.smtp", "User SMTP Setup Fields"),
        Item("Users Fields", "field.user.margin", "User Margin Field"),
        Item("Users Fields", "field.user.target", "User Target Field"),
        Item("Users Fields", "field.user.active", "Active Field"),

        Item("Roles & Rights", "roles.view", "Role Master View"),
        Item("Roles & Rights", "roles.manage", "Role Master Create/Edit/Delete"),
        Item("Roles & Rights", "permissions.manage", "Role Wise Rights Manage"),
        Item("Roles & Rights", "userpermissions.manage", "User Wise Rights Manage"),

        Item("Partner", "dealer.view", "Partner Menu View"),
        Item("Partner", "dealer.manage", "Partner Create/Edit/Delete"),
        Item("Partner Fields", "field.partner.name", "Partner Name Field"),
        Item("Partner Fields", "field.partner.contact", "Partner Contact Fields"),
        Item("Partner Fields", "field.partner.business", "Partner Total / Active / Sold / Business Columns"),

        Item("Product", "product.view", "Product Menu View"),
        Item("Product", "product.manage", "Product Create/Edit/Delete"),
        Item("Product Fields", "field.product.name", "Product Name Field"),
        Item("Product Fields", "field.product.version", "Version Field"),
        Item("Product Fields", "field.product.price", "Price Field"),

        Item("Stock", "stock.view", "Stock Menu View"),
        Item("Stock", "stock.manage", "Stock Create/Edit/Delete"),
        Item("Stock Fields", "field.stock.qty", "Stock Qty Field"),
        Item("Stock Fields", "field.stock.amount", "Stock Amount Field"),

        Item("Scheme", "scheme.view", "Scheme Menu View"),
        Item("Scheme", "scheme.manage", "Scheme Create/Edit/Delete"),
        Item("Commission", "commission.view", "Commission Menu View"),
        Item("Commission", "commission.manage", "Commission Manage"),
        Item("Notifications", "notifications.view", "Notifications View"),
        Item("Notifications", "notifications.send", "Notifications Send"),
        Item("Notifications", "notifications.delete", "Notifications Delete History"),
        Item("Inquiry Smart Features", "inquiry.attention.alert.view", "Unattended / Next Action Popup"),
        Item("Inquiry Smart Features", "inquiry.achievement.view", "Monthly Achievement Flash"),
        Item("Reports", "reports.ai", "AI Based Free Insights"),
        Item("Product Fields", "field.product.directprice", "Direct Customer Price Field"),
        Item("Product Fields", "field.product.partnerprice", "Partner Product Price Field"),
        Item("Stock", "stock.amountreport.view", "Stock Amount Report"),
        Item("Stock", "stock.bill.create", "Create Stock Bill"),
        Item("Chat", "chat.access", "Chat - Use Internal Chat"),
        Item("Chat", "chat.viewall", "Chat - View / Monitor All Conversations (Admin)"),
        Item("Chat", "chat.clear", "Chat - Clear Chat (My View Only)"),
        Item("Chat", "chat.delete", "Chat - Delete Chat (Particular Message / Delete All)"),

        Item("CRM Experience", "shortcuts.view", "Keyboard Shortcut List"),
        Item("CRM Experience", "help.view", "Contextual CRM Help"),
        Item("CRM Experience", "lock.screen.use", "Screen Lock / Unlock (Alt+Q)"),
        Item("Settings", "settings.view", "Settings View"),
        Item("Settings", "settings.manage", "Settings Manage")
    };

    private static PermissionItem Item(string group, string key, string label) => new()
    {
        GroupName = group,
        PermissionKey = key,
        PermissionLabel = label
    };
}
